{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flask-app-chart.fullname" . }}
  labels:
    {{- include "flask-app-chart.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host | quote }}
      http:
        paths:
          - path: {{ (index (index .Values.ingress.hosts 0).paths 0).path | default "/" }}
            pathType: {{ (index (index .Values.ingress.hosts 0).paths 0).pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "flask-app-chart.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
{{- end }}
