apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app-chart.fullname" . }}
  labels:
    {{- include "flask-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "flask-app-chart.selectorLabels" . | nindent 4 }}
